name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew  # 追加: 実行権限を与える

      - name: Build with Gradle
        run: ./gradlew build --info

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}  # YOUR_PERSONAL_ACCESS_TOKENには実際のアクセストークンを入力
          publish_dir: ./build/libs/
